"""
One-time migration for the "Vetting Panel vs Commissioners" change (guide section 5.3).

Zero behaviour change on day one: every existing commissioner is also made a panel member,
so an organisation is never left with an empty panel. The superadmin then trims the panel
(removes anyone who should not vet). Existing votes are untouched: they keep the voter's
student_id as their key, so they still belong to the same person (decision 14).

What it does, per organisation:
  1. For each voter with is_commissioner: create a panel_members record linked by student_id
     (is_member True), unless one already exists (idempotent).
  2. Reports organisations whose active panel would be under 3 (guide 7 item 6). The
     minimum is enforced when vetting opens, so this is a warning to act on before then.
  3. Writes one audit entry per organisation it changes.

Panel members are NOT given a password here. Credentials are issued by the superadmin
(the create/set-credentials endpoints), so nothing sensitive is generated by a script.
Members created here are marked must_change_password and inactive until credentials are set,
so they cannot log in by accident.

Usage (dry run is the default and changes nothing):
    python migrate_create_vetting_panel.py
    python migrate_create_vetting_panel.py --apply
    python migrate_create_vetting_panel.py --apply --org-id <org_id>

Env: MONGO_URL, MONGO_DB_NAME (same as the backend).
"""
import argparse
import asyncio
import os
import secrets
from datetime import datetime

import motor.motor_asyncio
from dotenv import load_dotenv

load_dotenv()
MONGO_URL = os.getenv("MONGO_URL", "mongodb://localhost:27017")
DB_NAME = os.getenv("MONGO_DB_NAME", "electiondbaccounting")
MIN_PANEL = 3


def _panel_id() -> str:
    return f"PM-{secrets.token_hex(6).upper()}"


async def main(apply: bool, only_org: str | None, db=None):
    # db is injectable so the migration can be tested against the in-memory database;
    # the CLI path below always builds the real client from MONGO_URL.
    if db is None:
        db = motor.motor_asyncio.AsyncIOMotorClient(MONGO_URL)[DB_NAME]
    org_names = {str(o["_id"]): o.get("name") or o.get("slug") or str(o["_id"])
                 async for o in db.organizations.find({})}

    commq = {"is_commissioner": True}
    if only_org:
        commq["org_id"] = only_org
    commissioners = [v async for v in db.voters.find(
        commq, {"student_id": 1, "full_name": 1, "org_id": 1, "phone_numbers": 1})]

    org_ids = sorted({c.get("org_id") for c in commissioners} | (
        {only_org} if only_org else {str(k) for k in org_names}), key=lambda x: str(x))

    print(f"{'APPLYING' if apply else 'DRY RUN'} on {DB_NAME}\n")
    short_orgs = 0
    created_total = 0
    for org_id in org_ids:
        label = org_names.get(org_id, org_id or "(no org)")
        mine = [c for c in commissioners if c.get("org_id") == org_id]

        existing_linked = set()
        async for p in db.panel_members.find(
                {"org_id": org_id, "is_member": True}, {"student_id": 1}):
            if p.get("student_id"):
                existing_linked.add(p["student_id"])

        to_create = [c for c in mine if c.get("student_id") not in existing_linked]
        active_panel = await db.panel_members.count_documents({"org_id": org_id, "active": True})
        projected = active_panel + len(to_create)

        print(f"[{label}]  commissioners: {len(mine)}  |  already on panel: "
              f"{len(mine) - len(to_create)}  |  to add: {len(to_create)}  |  projected panel: {projected}")
        for c in to_create:
            print(f"    + {c.get('full_name', '?')} ({c.get('student_id')}) becomes a panelist (member)")

        if projected < MIN_PANEL:
            short_orgs += 1
            print(f"    !! panel would have {projected} active panelist(s); minimum is {MIN_PANEL}. "
                  f"Add panelists before vetting opens, or vetting cannot be opened.")

        if apply and to_create:
            now = datetime.utcnow()
            docs = []
            for c in to_create:
                docs.append({
                    "org_id": org_id,
                    "panel_member_id": _panel_id(),
                    "full_name": c.get("full_name", ""),
                    "email": "",
                    "phone_numbers": c.get("phone_numbers", []),
                    "is_member": True,
                    "appointment_reason": "Migrated from commissioner role (guide 5.3)",
                    "affiliation": "",
                    "student_id": c["student_id"],
                    "access_expires_at": None,
                    "expires_with_phase": None,
                    "confidentiality_accepted_at": None,
                    "confidentiality_version": None,
                    # Inactive until the superadmin issues credentials; cannot log in before then.
                    "active": False,
                    "password_hash": "",
                    "must_change_password": True,
                    "temp_password_expires": None,
                    "added_by": "migration",
                    "added_at": now,
                    "removed_at": None,
                })
            await db.panel_members.insert_many(docs)
            created_total += len(docs)
            await db.audit_log.insert_one({
                "action": "vetting_panel_migrated", "actor": "migration",
                "details": {"created": [c.get("student_id") for c in to_create]},
                "org_id": org_id, "timestamp": now,
            })
            print(f"    {len(docs)} panel record(s) created (inactive until credentials are set); audit entry written")
        print()

    if not apply:
        print("Nothing changed. Re-run with --apply to create the panel records.")
    else:
        print(f"Created {created_total} panel record(s).")
    if short_orgs:
        print(f"{short_orgs} organisation(s) above would have fewer than {MIN_PANEL} panelists: "
              f"add panelists before opening vetting.")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="actually create the panel records (default: dry run)")
    ap.add_argument("--org-id", help="limit to one organization (string _id)")
    a = ap.parse_args()
    asyncio.run(main(a.apply, a.org_id))
